version: '3.7'
services:
  db:
    container_name: "db"
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: memberships
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
    ports:
      - "3306:3306"
volumes:
  db-data:

